---
dependencies:
  - { role: "bee-pollinator.base" }
  - { role: "azavea.swapfile" }
  - { role: "azavea.python", python_development: True }
  - { role: "azavea.pip" }
  - { role: "azavea.nodejs" }
  - { role: "azavea.phantomjs" }
  - { role: "bee-pollinator.monitoring", collectd_prefix: "collectd.app.", when: "['test'] | is_not_in(group_names)" }
  - { role: "bee-pollinator.celery" }
  - { role: "bee-pollinator.nginx" }
