---
- name: Create geoprocessing directory
  file: path="{{ geop_home }}"
        state=directory

- name: Download Spark Job Server geoprocessing JAR
  get_url: url="{{ geop_jar_url }}"
           dest="{{ geop_home }}/mmw-geoprocessing-{{ geop_version }}.jar"
