---
- name: Install Geospatial libraries
  apt: pkg={{ item }} state=present
  with_items:
    - "binutils=2.26*"
    - "libproj-dev=4.9.*"
    - "gdal-bin=1.11.*"
    - "libgdal1-dev=1.11.*"

- name: Install PostgreSQL client
  apt: pkg=postgresql-client-9.3

