---
- name: Install Geospatial libraries
  apt: pkg={{ item }} state=present
  with_items:
    - "binutils=2.24*"
    - "libproj-dev=4.8.0*"
    - "gdal-bin=1.10.1*"
    - "libgdal1-dev=1.10.1*"

- name: Install PostgreSQL client
  apt: pkg=postgresql-client-9.3

