---
- name: Configure application
  copy: content="{{ item.value }}"
        dest="{{ envdir_home }}/{{ item.key }}"
        owner=root
        group=icp
        mode=0750
  with_dict: "{{ app_config }}"
  notify:
    - Restart icp-app

- name: Configure Gunicorn settings
  template: src=gunicorn.py.j2 dest=/etc/icp.d/gunicorn.py
  notify:
    - Restart icp-app

- name: Configure Gunicorn service definition
  template: src=systemd-app.service.j2
            dest=/etc/systemd/system/icp-app.service
  notify:
    - Restart icp-app

- name: Enable Gunicorn service
  systemd: name=icp-app.service enabled=yes state=started daemon_reload=yes
