---
- name: Install application Python dependencies for development and test
  pip: requirements="{{ app_home }}/requirements/{{ item }}.txt"
  with_items:
    - development
    - test
  when: "['development', 'test'] | some_are_in(group_names)"
  notify:
    - Restart icp-app

- name: Install application Python dependencies for production
  pip: requirements="{{ app_home }}/requirements/production.txt"
  when: "['packer'] | is_in(group_names)"
  notify:
    - Restart icp-app

- name: Hack Python 2.7 to work with Ubuntu Xenial
  replace:
    path: /usr/local/lib/python2.7/dist-packages/django/contrib/gis/geos/libgeos.py
    regexp: geos_version\(\)\.decode\(\)
    replace: geos_version().split()[0].decode()
