---
- name: Install application Python dependencies for development and test
  pip: chdir="{{ celery_dir }}/requirements" requirements={{ item }}.txt
  with_items:
    - development
    - test
  when: "['development', 'test'] | some_are_in(group_names)"
  notify:
    - Restart Celery

- name: Install application Python dependencies for production
  pip: chdir="{{ celery_dir }}/requirements" requirements=production.txt
  when: "['packer'] | is_in(group_names)"
  notify:
    - Restart Celery
