---
dependencies:
  - { role: "bee-pollinator.base" }
  - { role: "azavea.python", python_development: True }
  - { role: "azavea.pip" }
  - { role: "bee-pollinator.monitoring", collectd_prefix: "collectd.worker.", when: "['test'] | is_not_in(group_names)" }
  - { role: "bee-pollinator.celery" }
