---
- hosts: monitoring-servers
  become: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - { role: "azavea.ntp" }
    - { role: "bee-pollinator.graphite", when: "['test'] | is_not_in(group_names)" }
    - { role: "bee-pollinator.logstash", when: "['test'] | is_not_in(group_names)" }
    - { role: "azavea.kibana", when: "['test'] | is_not_in(group_names)" }
