- src: azavea.ntp
  version: 0.1.1
  
- src: azavea.pip
  version: 2.0.0

- src: azavea.nodejs
  version: 0.3.0

- src: azavea.git
  version: 0.1.0

- src: azavea.nginx
  version: 0.3.1

- src: azavea.daemontools
  version: 0.1.0

- src: azavea.postgresql-support
  version: 0.4.0

- src: azavea.postgresql
  version: 1.0.0

- src: azavea.postgis
  version: 0.3.0

- src: azavea.redis
  version: 0.1.0

- src: azavea.graphite
  version: 0.6.1

- src: azavea.statsite
  version: 1.1.1

- src: azavea.phantomjs
  version: 0.1.0

- src: azavea.relp
  version: 0.1.2

- src: azavea.curator
  version: 0.1.0

- src: azavea.elasticsearch
  version: 0.2.0

- src: azavea.logstash
  version: 0.1.0

- src: azavea.kibana
  version: 0.3.1

- src: azavea.collectd
  version: 0.2.0

- src: azavea.build-essential
  version: 0.1.0

- src: azavea.beaver
  version: 1.0.1

- src: azavea.java
  version: 0.6.2

- src: azavea.docker
  version: 4.0.0

- src: azavea.python
  version: 0.1.0

- src: azavea.python-security
  version: 1.0.0

- src: azavea.unzip
  version: 0.1.2

- src: azavea.apache2
  version: 0.2.4

- src: azavea.memcached
  version: 0.1.0

- src: azavea.swapfile
  version: 0.1.0
