---
- hosts: services
  become: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Install ACL utilities
      apt: pkg="acl" state=present

  roles:
    - { role: "bee-pollinator.postgresql", when: "['development', 'test'] | some_are_in(group_names)" }
    - { role: "bee-pollinator.pgweb", when: "['development', 'test'] | some_are_in(group_names)" }
    - { role: "azavea.redis", when: "['development', 'test'] | some_are_in(group_names)" }
    - { role: "bee-pollinator.graphite", when: "['test'] | is_not_in(group_names)" }
    - { role: "bee-pollinator.logstash", when: "['test'] | is_not_in(group_names)" }
    - { role: "azavea.kibana", when: "['test'] | is_not_in(group_names)" }
