---
- hosts: workers
  become: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - { role: "bee-pollinator.celery-worker" }
    - { role: "bee-pollinator.geoprocessing" }
